// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Ca3Cwya1j2GYuEXE0XnEupxwq7_nc2g',
    appId: '1:689685881484:web:5af4a630d3708ab44011a9',
    messagingSenderId: '689685881484',
    projectId: 'flutter-test-80609',
    authDomain: 'flutter-test-80609.firebaseapp.com',
    storageBucket: 'flutter-test-80609.appspot.com',
    measurementId: 'G-5WNKKL49BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtyMGUFZmldiX47fMTjn-ySb0k-A1XlvM',
    appId: '1:689685881484:android:c33b7defea6c2e144011a9',
    messagingSenderId: '689685881484',
    projectId: 'flutter-test-80609',
    storageBucket: 'flutter-test-80609.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhbmcpEY-URq-5VF0g5Rh3Jkd1SxGKRvA',
    appId: '1:689685881484:ios:3b9ca42fba964d6c4011a9',
    messagingSenderId: '689685881484',
    projectId: 'flutter-test-80609',
    storageBucket: 'flutter-test-80609.appspot.com',
    iosBundleId: 'com.example.finalFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhbmcpEY-URq-5VF0g5Rh3Jkd1SxGKRvA',
    appId: '1:689685881484:ios:3b9ca42fba964d6c4011a9',
    messagingSenderId: '689685881484',
    projectId: 'flutter-test-80609',
    storageBucket: 'flutter-test-80609.appspot.com',
    iosBundleId: 'com.example.finalFlutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7Ca3Cwya1j2GYuEXE0XnEupxwq7_nc2g',
    appId: '1:689685881484:web:0c61da1c4be865894011a9',
    messagingSenderId: '689685881484',
    projectId: 'flutter-test-80609',
    authDomain: 'flutter-test-80609.firebaseapp.com',
    storageBucket: 'flutter-test-80609.appspot.com',
    measurementId: 'G-GNLM4L7F8B',
  );
}
